version: "3.8"

services:
  nestjs:
    container_name: api
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgresql
      - mongodb
  postgresql:
    container_name: principal-database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SolanaGateway
  mongodb:
    container_name: log-database
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
